<?php
/**
 * Implements hook_block().
 *
 * @param string $op
 * @param int $delta
 * @param array $edit
 * @return string
 */
function balanceonline_og_like_block($op = 'list', $delta = 0, $edit = array()) {
	switch ($op) {
		case 'list':
			$blocks[0]['info'] = 'Balance ' . t('OG Like');
			$blocks[1]['info'] = 'Balance ' . t('OG Like Members');
			return $blocks;

		case 'view':
			switch($delta) {
				case 0:
					$block['content'] = balanceonline_og_like_block_content();
				break;
				case 1:
					$block['content'] = balanceonline_og_like_members_block_content();
				break;
			}

			return $block;
	}
}

/**
 * Flag block content
 * 
 * @return string
 */
function balanceonline_og_like_block_content() {
	// If in single node page
	if (arg(0) == 'node' && is_numeric(arg(1))) {
	  // Load node to get nid
	  $node = node_load(arg(1));
	  // Print Flag link
	  return '<span class="balance-og-like"></span>' . flag_create_link('gefallen', $node->nid);
	}
}

/**
 * Flag block content
 * 
 * @return string
 */
function balanceonline_og_like_members_block_content() {
	// If in single node page
	if (arg(0) == 'node' && is_numeric(arg(1))) {
	  // Load node to get nid
	  $users = flag_get_content_flags('node', arg(1));
		if(!empty($users)) {
			foreach(array_keys($users) as $u) {
		    $account = user_load(array('uid' => $u));
		    $list[] = theme('user_picture', $account) .' '. theme('username', $account);
			}
			return theme('item_list', $list);
		}
	}
}
